#pragma once

#include <windows.h>
#include <process.h>

#include "simapi.h"	// before Qt headers!
#include "stl.h"

#include <qglobal.h>

#include <qapplication.h>
#include <qbitmap.h>
#include <qbutton.h>
#include <qclipboard.h>
#include <qcursor.h>
#include <qdialog.h>
#include <qdragobject.h>
#include <qframe.h>
#include <qfile.h>
#include <qfiledialog.h>
#include <qimage.h>
#include <qlabel.h>
#include <qlayout.h>
#include <qlineedit.h>
#include <qlistview.h>
#include <qmultilineedit.h>
#include <qobject.h>
#include <qobjectlist.h>
#include <qpainter.h>
#include <qpopupmenu.h>
#include <qpushbutton.h>
#include <qsocketnotifier.h>
#include <qstring.h>
#include <qstringlist.h>
#include <qtabbar.h>
#include <qtabwidget.h>
#include <qthread.h>
#include <qtimer.h>
#include <qtooltip.h>
#include <qvalidator.h>

#ifndef NO_QT_MOC_HEADER
#include <qmetaobject.h>
#include <private/qucomextra_p.h>
#include <qsignalslotimp.h>
#endif

#include "arcfg.h"
#include "arcfgbase.h"
#include "autoreply.h"
#include "autoreplybase.h"
#include "cfgdlg.h"
#include "cfgdlgbase.h"
#include "cmenu.h"
#include "commands.h"
#include "connectionsettings.h"
#include "connectionsettingsbase.h"
#include "connectwnd.h"
#include "connectwndbase.h"
#include "container.h"
#include "core.h"
#include "declinedlg.h"
#include "declinedlgbase.h"
#include "editmail.h"
#include "editmailbase.h"
#include "editphone.h"
#include "editphonebase.h"
#include "filecfg.h"
#include "filecfgbase.h"
#include "filetransfer.h"
#include "filetransferbase.h"
#include "history.h"
#include "historycfg.h"
#include "historycfgbase.h"
#include "historywnd.h"
#include "interfacecfg.h"
#include "interfacecfgbase.h"
#include "kpopup.h"
#include "logindlg.h"
#include "logindlgbase.h"
#include "maininfo.h"
#include "maininfobase.h"
#include "mainwin.h"
#include "manager.h"
#include "managerbase.h"
#include "msgauth.h"
#include "msgcfg.h"
#include "msgcfgbase.h"
#include "msgcontacts.h"
#include "msgedit.h"
#include "msgfile.h"
#include "msggen.h"
#include "msgrecv.h"
#include "msgsms.h"
#include "msgurl.h"
#include "msgview.h"
#include "newprotocol.h"
#include "newprotocolbase.h"
#include "nonim.h"
#include "nonimbase.h"
#include "pagerbase.h"
#include "pagerdetails.h"
#include "phonebase.h"
#include "phonedetails.h"
#include "plugincfg.h"
#include "plugincfgbase.h"
#include "prefcfg.h"
#include "prefcfgbase.h"
#include "search.h"
#include "searchall.h"
#include "searchallbase.h"
#include "searchbase.h"
#include "smscfg.h"
#include "smscfgbase.h"
#include "status.h"
#include "statuswnd.h"
#include "tmpl.h"
#include "toolbarcfg.h"
#include "toolsetup.h"
#include "toolsetupbase.h"
#include "usercfg.h"
#include "userhistorycfg.h"
#include "userhistorycfgbase.h"
#include "userlist.h"
#include "userview.h"
#include "userviewcfg.h"
#include "userviewcfgbase.h"
#include "userwnd.h"
