; Script generated by the My Inno Setup Extensions Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=Qt
AppVerName=Qt 2.3.1
DefaultDirName={pf}\SIM
DisableProgramGroupPage=yes
DisableStartupPrompt=yes
DisableReadyPage=yes
Compression=bzip/9
AppId=SIM
AppMutex=SIM_Mutex
OutputBaseFilename=qt

[Files]
Source: "C:\qt\bin\qt-mt230nc.dll"; DestDir: "{app}"

