.TH "SIM" "1" "June 29, 2006" "SIM-IM Team" "Simple Instant Messenger"
.SH NAME
SIM \- Simple Instant Messenger
.SH SYNOPSIS
.B sim
[\fIQt-options\fR] [\fIKDE-options\fR] [\fIoptions\fR]
.SH DESCRIPTION
ICQ client
.SS "Generic options:"
.TP
\fB\-\-help\fR
Show help about options
.TP
\fB\-\-help\-qt\fR
Show Qt specific options
.TP
\fB\-\-help\-kde\fR
Show KDE specific options
.TP
\fB\-\-help\-all\fR
Show all options
.TP
\fB\-\-author\fR
Show author information
.TP
\fB\-v\fR, \fB\-\-version\fR
Show version information
.TP
\fB\-\-license\fR
Show license information
.TP
\fB\-\-nofork\fR
Do not fork from current console.
.TP
\fB\-\-\fR
End of options
.SH OPTIONS
.TP
\fB\-b\fR <dir>
Directory for files
.TP
\fB\-d\fR <loglevel>
Loglevel
.TP
\fB\-m\fR
Show Monitor Window.
.TP
\fB\-s\fR <socket>
Control socket
.SH "SEE ALSO"
Information and help about SIM-IM can be found at project's site
.B http://sim-im.org/
.PP
SIM is based on KDE and QT. Information about KDE project can be found at 
.B http://kde.org/
.PP
The full documentation for
.B Qt
is maintained as a Texinfo manual.  If the
.B info
and
.B Qt
programs are properly installed at your site, the command
.IP
.B info Qt
.PP
should give you access to the complete manual.
More information about Qt can be found at Trolltech's site
.B http://doc.trolltech.com/qt.html

.SH "AUTHORS"
SIM-IM Team, see http://sim-im.org/ and /usr/share/doc/sim/AUTHORS.sim
