; Script generated by the My Inno Setup Extensions Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=expat
AppVerName=expat 1.95.6
DefaultDirName={pf}\SIM
DisableProgramGroupPage=yes
DisableStartupPrompt=yes
DisableReadyPage=yes
Compression=bzip/9
AppId=SIM
AppMutex=SIM_Mutex
OutputBaseFilename=expat

[Files]
Source: "C:\windows\libexpat.dll"; DestDir: "{app}"

