; Script generated by the My Inno Setup Extensions Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=msvcrt
AppVerName=msvcrt
DefaultDirName={pf}\SIM
DisableProgramGroupPage=yes
DisableStartupPrompt=yes
DisableReadyPage=yes
Compression=bzip/9
AppId=SIM
AppMutex=SIM_Mutex
OutputBaseFilename=msvcrt

[Files]
Source: "msvcrt.dll"; DestDir: "{sys}"; Flags: uninsneveruninstall
Source: "msvcp60.dll"; DestDir: "{sys}"; Flags: uninsneveruninstall

