#include "country.h"

const ext_info Languages[] =
    {
        {"Arabic", 1},
        {"Bhojpuri", 2},
        {"Bulgarian", 3},
        {"Burmese", 4},
        {"Cantonese", 5},
        {"Catalan", 6},
        {"Chinese", 7},
        {"Croatian", 8},
        {"Czech", 9},
        {"Danish", 10},
        {"Dutch", 11},
        {"English", 12},
        {"Esperanto", 13},
        {"Estonian", 14},
        {"Farsi", 15},
        {"Finnish", 16},
        {"French", 17},
        {"Gaelic", 18},
        {"German", 19},
        {"Greek", 20},
        {"Hebrew", 21},
        {"Hindi", 22},
        {"Hungarian", 23},
        {"Icelandic", 24},
        {"Indonesian", 25},
        {"Italian", 26},
        {"Japanese", 27},
        {"Khmer", 28},
        {"Korean", 29},
        {"Lao", 30},
        {"Latvian", 31},
        {"Lithuanian", 32},
        {"Malay", 33},
        {"Norwegian", 34},
        {"Polish", 35},
        {"Portuguese", 36},
        {"Romanian", 37},
        {"Russian", 38},
        {"Serbian", 39},
        {"Slovak", 40},
        {"Slovenian", 41},
        {"Somali", 42},
        {"Spanish", 43},
        {"Swahili", 44},
        {"Swedish", 45},
        {"Tagalog", 46},
        {"Tatar", 47},
        {"Thai", 48},
        {"Turkish", 49},
        {"Ukrainian", 50},
        {"Urdu", 51},
        {"Vietnamese", 52},
        {"Yiddish", 53},
        {"Yoruba", 54},
        {"Taiwanese", 55},
        {"Afrikaans", 56},
        {"Persian", 57},
        {"Albanian", 58},
        {"Armenian", 59},
        {"", 0}
    };

const ext_info Countries[] =
    {
        {"Afghanistan", 93 },
        {"Albania", 355 },
        {"Algeria", 213 },
        {"American Samoa", 684 },
        {"Andorra", 376 },
        {"Angola", 244 },
        {"Anguilla", 101 },
        {"Antigua", 102 },
        {"Argentina", 54 },
        {"Armenia", 374 },
        {"Aruba", 297 },
        {"Ascension Island", 247 },
        {"Australia", 61 },
        {"Australian Antarctic Territory", 6721 },
        {"Austria", 43 },
        {"Azerbaijan", 994 },
        {"Bahamas", 103 },
        {"Bahrain", 973 },
        {"Bangladesh", 880 },
        {"Barbados", 104 },
        {"Barbuda", 120 },
        {"Belarus", 375 },
        {"Belgium", 32 },
        {"Belize", 501 },
        {"Benin", 229 },
        {"Bermuda", 105 },
        {"Bhutan", 975 },
        {"Bolivia", 591 },
        {"Bosnia and Herzegovina", 387 },
        {"Botswana", 267 },
        {"Brazil", 55 },
        {"British Virgin Islands", 106 },
        {"Brunei", 673 },
        {"Bulgaria", 359 },
        {"Burkina Faso", 226 },
        {"Burundi", 257 },
        {"Cambodia", 855 },
        {"Cameroon", 237 },
        {"Canada", 107 },
        {"Cape Verde Islands", 238 },
        {"Cayman Islands", 108 },
        {"Central African Republic", 236 },
        {"Chad", 235 },
        {"Chile", 56 },
        {"China", 86 },
        {"Christmas Island", 672 },
        {"Cocos-Keeling Islands", 6101 },
        {"Colombia", 57 },
        {"Comoros", 2691 },
        {"Congo", 242 },
        {"Cook Islands", 682 },
        {"Costa Rica", 506 },
        {"Croatia", 385 },
        {"Cuba", 53 },
        {"Cyprus", 357 },
        {"Czech Republic", 42 },
        {"Denmark", 45 },
        {"Diego Garcia", 246 },
        {"Djibouti", 253 },
        {"Dominica", 109 },
        {"Dominican Republic", 110 },
        {"Ecuador", 593 },
        {"Egypt", 20 },
        {"El Salvador", 503 },
        {"Equatorial Guinea", 240 },
        {"Eritrea", 291 },
        {"Estonia", 372 },
        {"Ethiopia", 251 },
        {"Faeroe Islands", 298 },
        {"Falkland Islands", 500 },
        {"Fiji Islands", 679 },
        {"Finland", 358 },
        {"France", 33 },
        {"French Antilles", 5901 },
        {"French Guiana", 594 },
        {"French Polynesia", 689 },
        {"Gabon", 241 },
        {"Gambia", 220 },
        {"Georgia", 995 },
        {"Germany", 49 },
        {"Ghana", 233 },
        {"Gibraltar", 350 },
        {"Greece", 30 },
        {"Greenland", 299 },
        {"Grenada", 111 },
        {"Guadeloupe", 590 },
        {"Guam", 671 },
        {"Guantanamo Bay", 5399 },
        {"Guatemala", 502 },
        {"Guinea", 224 },
        {"Guinea-Bissau", 245 },
        {"Guyana", 592 },
        {"Haiti", 509 },
        {"Honduras", 504 },
        {"Hong Kong", 852 },
        {"Hungary", 36 },
        {"INMARSAT (Atlantic-East)", 871 },
        {"INMARSAT (Atlantic-West)", 874 },
        {"INMARSAT (Indian)", 873 },
        {"INMARSAT (Pacific)", 872 },
        {"INMARSAT", 870 },
        {"Iceland", 354 },
        {"India", 91 },
        {"Indonesia", 62 },
        {"International Freephone Service", 800 },
        {"Iran", 98 },
        {"Iraq", 964 },
        {"Ireland", 353 },
        {"Israel", 972 },
        {"Italy", 39 },
        {"Ivory Coast", 225 },
        {"Jamaica", 112 },
        {"Japan", 81 },
        {"Jordan", 962 },
        {"Kazakhstan", 705 },
        {"Kenya", 254 },
        {"Kiribati Republic", 686 },
        {"Korea (North)", 850 },
        {"Korea (Republic of)", 82 },
        {"Kuwait", 965 },
        {"Kyrgyz Republic", 706 },
        {"Laos", 856 },
        {"Latvia", 371 },
        {"Lebanon", 961 },
        {"Lesotho", 266 },
        {"Liberia", 231 },
        {"Libya", 218 },
        {"Liechtenstein", 4101 },
        {"Lithuania", 370 },
        {"Luxembourg", 352 },
        {"Macau", 853 },
        {"Madagascar", 261 },
        {"Malawi", 265 },
        {"Malaysia", 60 },
        {"Maldives", 960 },
        {"Mali", 223 },
        {"Malta", 356 },
        {"Marshall Islands", 692 },
        {"Martinique", 596 },
        {"Mauritania", 222 },
        {"Mauritius", 230 },
        {"Mayotte Island", 269 },
        {"Mexico", 52 },
        {"Micronesia, Federated States of", 691 },
        {"Moldova", 373 },
        {"Monaco", 377 },
        {"Mongolia", 976 },
        {"Montserrat", 113 },
        {"Morocco", 212 },
        {"Mozambique", 258 },
        {"Myanmar", 95 },
        {"Namibia", 264 },
        {"Nauru", 674 },
        {"Nepal", 977 },
        {"Netherlands Antilles", 599 },
        {"Netherlands", 31 },
        {"Nevis", 114 },
        {"New Caledonia", 687 },
        {"New Zealand", 64 },
        {"Nicaragua", 505 },
        {"Niger", 227 },
        {"Nigeria", 234 },
        {"Niue", 683 },
        {"Norfolk Island", 6722 },
        {"Norway", 47 },
        {"Oman", 968 },
        {"Pakistan", 92 },
        {"Palau", 680 },
        {"Panama", 507 },
        {"Papua New Guinea", 675 },
        {"Paraguay", 595 },
        {"Peru", 51 },
        {"Philippines", 63 },
        {"Poland", 48 },
        {"Portugal", 351 },
        {"Puerto Rico", 121 },
        {"Qatar", 974 },
        {"Republic of Macedonia", 389 },
        {"Reunion Island", 262 },
        {"Romania", 40 },
        {"Rota Island", 6701 },
        {"Russia", 7 },
        {"Rwanda", 250 },
        {"Saint Lucia", 122 },
        {"Saipan Island", 670 },
        {"San Marino", 378 },
        {"Sao Tome and Principe", 239 },
        {"Saudi Arabia", 966 },
        {"Senegal Republic", 221 },
        {"Seychelle Islands", 248 },
        {"Sierra Leone", 232 },
        {"Singapore", 65 },
        {"Slovak Republic", 4201 },
        {"Slovenia", 386 },
        {"Solomon Islands", 677 },
        {"Somalia", 252 },
        {"South Africa", 27 },
        {"Spain", 34 },
        {"Sri Lanka", 94 },
        {"St. Helena", 290 },
        {"St. Kitts", 115 },
        {"St. Pierre and Miquelon", 508 },
        {"St. Vincent and the Grenadines", 116 },
        {"Sudan", 249 },
        {"Suriname", 597 },
        {"Swaziland", 268 },
        {"Sweden", 46 },
        {"Switzerland", 41 },
        {"Syria", 963 },
        {"Taiwan, Republic of China", 886 },
        {"Tajikistan", 708 },
        {"Tanzania", 255 },
        {"Thailand", 66 },
        {"Tinian Island", 6702 },
        {"Togo", 228 },
        {"Tokelau", 690 },
        {"Tonga", 676 },
        {"Trinidad and Tobago", 117 },
        {"Tunisia", 216 },
        {"Turkey", 90 },
        {"Turkmenistan", 709 },
        {"Turks and Caicos Islands", 118 },
        {"Tuvalu", 688 },
        {"USA", 1 },
        {"Uganda", 256 },
        {"Ukraine", 380 },
        {"United Arab Emirates", 971 },
        {"United Kingdom", 44 },
        {"United States Virgin Islands", 123 },
        {"Uruguay", 598 },
        {"Uzbekistan", 711 },
        {"Vanuatu", 678 },
        {"Vatican City", 379 },
        {"Venezuela", 58 },
        {"Vietnam", 84 },
        {"Wallis and Futuna Islands", 681 },
        {"Western Samoa", 685 },
        {"Yemen", 967 },
        {"Yugoslavia", 381 },
        {"Zaire", 243 },
        {"Zambia", 260 },
        {"Zimbabwe", 263 },
        {"", 0 },
    };

const pager_provider Providers[] =
    {
        { "(Russia) F1", "pager.oryol.ru" },
        { "(Russia) FCN (Full Cray Neva)", "pager.fcn.ru" },
        { "(Russia) Multi-Page", "pager.multi-page.ru" },
        { "(Russia) Mobile Telecom", "pager.mobiletelecom.ru" },
        { "(Russia) Mobile Telecom (subject)", "notify.mobiletelecom.ru" },
        { "(USA) Ameritech/SBC", "paging.acswireless.com" },
        { "(USA) Arch", "epage.arch.com" },
        { "(USA) AT&T", "mobile.att.net" },
        { "", "" }
    };

const ext_info Interests[] =
    {
        { "Art", 100  },
        { "Cars", 101  },
        { "Celebrity Fans", 102  },
        { "Collections", 103  },
        { "Computers", 104  },
        { "Culture & Literature", 105 },
        { "Fitness", 106  },
        { "Games", 107  },
        { "Hobbies", 108  },
        { "ICQ - Providing Help", 109  },
        { "Internet", 110  },
        { "Lifestyle", 111  },
        { "Movies/TV", 112  },
        { "Music", 113  },
        { "Outdoor Activities", 114  },
        { "Parenting", 115  },
        { "Pets/Animals", 116  },
        { "Religion", 117  },
        { "Science/Technology", 118  },
        { "Skills", 119  },
        { "Sports", 120  },
        { "Web Design", 121  },
        { "Nature and Environment", 122  },
        { "News & Media", 123  },
        { "Government", 124  },
        { "Business & Economy", 125  },
        { "Mystics", 126  },
        { "Travel", 127  },
        { "Astronomy", 128  },
        { "Space", 129  },
        { "Clothing", 130  },
        { "Parties", 131  },
        { "Women", 132  },
        { "Social science", 133  },
        { "60's", 134  },
        { "70's", 135  },
        { "80's", 136  },
        { "50's", 137  },
        { "Finance and corporate", 138  },
        { "Entertainment", 139  },
        { "Consumer electronics", 140  },
        { "Retail stores", 141  },
        { "Health and beauty", 142  },
        { "Media", 143  },
        { "Household products", 144  },
        { "Mail order catalog", 145  },
        { "Business services", 146  },
        { "Audio and visual", 147  },
        { "Sporting and athletic", 148  },
        { "Publishing", 149  },
        { "Home automation", 150  },
        { "", 0  }
    };

const ext_info Affilations[] =
    {
        { "Alumni Org.", 200 },
        { "Charity Org.", 201 },
        { "Club/Social Org.", 202 },
        { "Community Org.", 203 },
        { "Cultural Org.", 204 },
        { "Fan Clubs", 205 },
        { "Fraternity/Sorority", 206 },
        { "Hobbyists Org.", 207 },
        { "International Org.", 208 },
        { "Nature and Environment Org.", 209 },
        { "Professional Org.", 210 },
        { "Scientific/Technical Org.", 211 },
        { "Self Improvement Group", 212 },
        { "Spiritual/Religious Org.", 213 },
        { "Sports Org.", 214 },
        { "Support Org.", 215 },
        { "Trade and Business Org.", 216 },
        { "Union", 217 },
        { "Volunteer Org.", 218 },
        { "Other", 299 },
        { "", 0 }
    };

const ext_info Occupations[] =
    {
        { "Academic", 1  },
        { "Administrative", 2  },
        { "Art/Entertainment", 3  },
        { "College Student", 4  },
        { "Computers", 5  },
        { "Community & Social", 6  },
        { "Education", 7  },
        { "Engineering", 8  },
        { "Financial Services", 9  },
        { "Government", 10  },
        { "High School Student", 11  },
        { "Home", 12  },
        { "ICQ - Providing Help", 13  },
        { "Law", 14  },
        { "Managerial", 15  },
        { "Manufacturing", 16  },
        { "Medical/Health", 17  },
        { "Military", 18  },
        { "Non-Goverment Organisation", 19  },
        { "Other services", 20  },
        { "Professional", 21  },
        { "Retail", 22  },
        { "Retired", 23  },
        { "Science & Research", 24  },
        { "Sports", 25  },
        { "Technical", 26  },
        { "University student", 27  },
        { "Web building", 28  },
        { "", 0  }
    };

const ext_info Pasts[] =
    {
        { "Elementary School", 300  },
        { "High School", 301  },
        { "College", 302  },
        { "University", 303  },
        { "Military", 304  },
        { "Past Work Place", 305  },
        { "Past Organization", 306  },
        { "Other", 399  },
        { "", 0  }
    };

const ext_info Genders[] =
    {
        { "Female", 1 },
        { "Male", 2 },
        { "", 0 }
    };

const ext_info Ages[] =
    {
        { "18-22", 1 },
        { "23-29", 2 },
        { "30-39", 3 },
        { "40-49", 4 },
        { "50-59", 5 },
        { "> 60", 6 },
        { "", 0 }
    };


const ext_info *languages = Languages;
const ext_info *countries = Countries;
const pager_provider *providers = Providers;
const ext_info *interests = Interests;
const ext_info *occupations = Occupations;
const ext_info *pasts = Pasts;
const ext_info *affilations = Affilations;
const ext_info *genders = Genders;
const ext_info *ages = Ages;


